# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: "SpacyNLP"
    # language model to load
    # model: "en_core_web_lg"
    model: "en_core_web_trf" # based on roberta
    case_sensitive: False
  # - name: WhitespaceTokenizer
  - name: "SpacyTokenizer"
  #   # Flag to check whether to split intents
  #   "intent_tokenization_flag": False
  #   # Symbol on which intent should be split
  #   "intent_split_symbol": "_"
  #   # Regular expression to detect tokens
  #   "token_pattern": None
  # to activate
  # - name: RegexFeaturizer
  # - name: LexicalSyntacticFeaturizer
  - name: SpacyFeaturizer

  # - name: LanguageModelFeaturizer
  #   # Name of the language model to use
  #   model_name: "bert"
  #   # Pre-Trained weights to be loaded
  #   model_weights: "rasa/LaBSE"

    # An optional path to a directory from which
    # to load pre-trained model weights.
    # If the requested model is not found in the
    # directory, it will be downloaded and
    # cached in this directory for future use.
    # The default value of `cache_dir` can be
    # set using the environment variable
    # `TRANSFORMERS_CACHE`, as per the
    # Transformers library.
    # cache_dir: null

  
  # - name: CRFEntityExtractor
  - name: "SpacyEntityExtractor"
    # dimensions to extract
    dimensions: ["PERSON", "ORDINAL", "ORG"]
  - name: RegexEntityExtractor
  - name: CountVectorsFeaturizer
    stop_words: ["the", "a", "an"]
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
